using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace Uralstech.UGemini.Models.Generation.Tools.CodeExecution
{
    /// <summary>
    /// Code generated by the model that is meant to be executed, and the result returned to the model.
    /// </summary>
    /// <remarks>
    /// Only generated when using the <see cref="Declaration.GeminiCodeExecution"/> tool,
    /// in which the code will be automatically executed, and a corresponding <see cref="GeminiCodeExecutionResult"/> will also be generated.
    /// </remarks>
    [JsonObject(NamingStrategyType = typeof(CamelCaseNamingStrategy))]
    public class GeminiExecutableCode
    {
        /// <summary>
        /// Programming language of the <see cref="Code"/>.
        /// </summary>
        public GeminiCodeExecutionLanguage Language;

        /// <summary>
        /// The code to be executed.
        /// </summary>
        public string Code;
    }
}