using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace Uralstech.UGemini.Models.Generation.Tools.Declaration
{
    /// <summary>
    /// Tool that executes code generated by the model, and automatically returns the result to the model.
    /// </summary>
    /// <remarks>
    /// See <see cref="CodeExecution.GeminiExecutableCode"/> and <see cref="CodeExecution.GeminiCodeExecutionResult"/>
    /// which are only generated when using this tool.
    /// </remarks>
    [JsonObject(NamingStrategyType = typeof(CamelCaseNamingStrategy))]
    public class GeminiCodeExecution { }
}